#!/bin/sh
KVEM_HOME=$(dirname $0)
KVEM_HOME=$(cd "$KVEM_HOME" 2> /dev/null 1>&2  && pwd -P)
KVEM_HOME=${KVEM_HOME%%/bin}

if [ -f "$KVEM_HOME/.org.opensolaris,pkg/nextInstall" ]
then
	last_known_reboot=`cat "$KVEM_HOME/.org.opensolaris,pkg/lastBoot"`
	last_reboot=`who -b`

	if [[ "$last_reboot" != "$last_known_reboot" ]] 
	then
    	open -W "$KVEM_HOME/Updater.app"
		if [ -f "$KVEM_HOME/.org.opensolaris,pkg/nextInstall" ]
		then
			#installation failed
			exit 1
		fi

	fi
fi

function stop_child {
    kill ${CHILD_PID}
    wait ${CHILD_PID}
}

DYLD_LIBRARY_PATH=${DYLD_LIBRARY_PATH}:${KVEM_HOME}/bin java  -classpath "$KVEM_HOME/lib/jsr172_1.0.jar:%TOOLS_JAR%:$KVEM_HOME/toolkit-lib/modules/bootstrap/code/bootstrap.jar:$KVEM_HOME/toolkit-lib/modules/bootstrap/code/log4j-1.2.15.jar" -Dlog4j.configuration="file:$KVEM_HOME/toolkit-lib/process/wscompile/conf/log4j.xml" -Dmodules.dir="$KVEM_HOME/toolkit-lib" -Dprocess=process/wscompile -Dtoolkit.home="$KVEM_HOME" -Demulator.home="$KVEM_HOME" -Demulator.lib="$KVEM_HOME/emulator-lib" -Dsystem.properties="$KVEM_HOME/toolkit-lib/platform.properties,$KVEM_HOME/toolkit-lib/modules/bootstrap/conf/system.properties,$KVEM_HOME/toolkit-lib/generated.properties" -Dmain.class=com.sun.jme.toolkit.ws.WSCompile -Dfile.encoding=UTF8 -Xdock:name="wscompile" com.sun.jme.toolkit.bootstrap.Container -cldc1.1 "$@" </dev/stdin &
CHILD_PID=$!
trap stop_child HUP INT QUIT ABRT KILL TERM
wait ${CHILD_PID}
